// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjgkXoxYM9Gj7zK5i6yB2-pDPVpArExRU',
    appId: '1:316084797142:web:07f04debe12b34add49377',
    messagingSenderId: '316084797142',
    projectId: 'busmapdhaka-471121',
    authDomain: 'busmapdhaka-471121.firebaseapp.com',
    storageBucket: 'busmapdhaka-471121.firebasestorage.app',
    measurementId: 'G-XN3VJTG49Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6l97KtX4iqmoUTnLT7UR3bnVrUQ5Gl_0',
    appId: '1:316084797142:android:abf146bc4a6e70e0d49377',
    messagingSenderId: '316084797142',
    projectId: 'busmapdhaka-471121',
    storageBucket: 'busmapdhaka-471121.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjgkXoxYM9Gj7zK5i6yB2-pDPVpArExRU',
    appId: '1:316084797142:web:11655f8838fbd883d49377',
    messagingSenderId: '316084797142',
    projectId: 'busmapdhaka-471121',
    authDomain: 'busmapdhaka-471121.firebaseapp.com',
    storageBucket: 'busmapdhaka-471121.firebasestorage.app',
    measurementId: 'G-7H5GT1ZCME',
  );

}